# Generated by Django 4.2.2 on 2023-06-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(default=None, max_length=100)),
                (
                    "last_name",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "employee_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discrepancy_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("WFH", "WFH"),
                            ("Attendance", "Attendance"),
                            ("Overtime", "Overtime"),
                            ("Leave", "Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode_of_marking",
                    models.CharField(
                        choices=[
                            ("Biometric", "Biometric"),
                            ("Connecto", "Connecto"),
                            ("OneThing", "OneThing"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField()),
                ("Date", models.DateField()),
                (
                    "reporting_person",
                    models.CharField(
                        choices=[
                            ("Sourabh Soni", "Sourabh Soni"),
                            ("Sunil More", "Sunil More"),
                            ("Santosh", "Santosh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Reporting_person_remark", models.CharField(max_length=150)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
